 !solve_mir.script  -- Run SOLVE on an MIR dataset
 TITLE         SOLVE     29-Oct-23                                             
 LOGFILE solve.logfile
 SOLVEFILE     dataset_1_scale.log                                             
 !Space group information:
 CELL     57.615    57.615   150.808    90.000    90.000    90.000
 SYMFILE       /usr/local/phenix-1.20.1-4487/modules/solve_resolve/ext_ref_file
 FFTGRID      0   143   144     0   143   144     0    40   324
 PATTGRID      0    72   144     0    72   144     0   162   324
 RESOLUTION    1.550000       1000.000    
 INFILE        mad_fbar.scl                                                    
 QUICKER
 IMADPHASE            0
 NNATF            1
 NNATS            2
 
 ! New atom types:
 NEWATOMTYPE ANO1
 AVAL         0.00000        0.00000        0.00000        0.00000
 BVAL         0.00000        0.00000        0.00000        0.00000
 CVAL         0.00000
 FPRIMV         0.01000
 FPRPRV         4.50000
 
 IHEAVYPROC            5
 NREP            5
 ! Information on            1  derivatives:
 
 DERIVATIVE            1
 LABEL         set 1                                                           
 NCOLFBAR            1
 NCOLSFBAR            2
 NCOLDELF            3
 NCOLSDELF            4
 INANO
 ANOONLY
 ! Heavy atoms for this derivative:
 !  ----------- ATOM ANO1 ----------
 ATOMNAME ANO1
 OCCUPANCY   0.1000000    
 BVALUE    35.00000    
 REFINEALL
 
 ! Information for HASSP and SOLVE
 IHASSPTYPE           5
 SEARCHREGION  0.000 0.993 0.000 0.993 0.000 0.123
 ICRMAX           20
 NTOPHASSP           30
 NTOPFOUR           40
 NTOPDERIV            5
 NSOLSITE           15
 NSEEDTEST           10
 NSEEDSOLVE            5
 NTOPSOLVE            5
 NTOL_SITE            8
 NTOL_SOLN            2
 ACCEPTANCE   0.2000000    
 DELETE
 INVERSE
 SOLVE
 QUICKER
